name: "Naver Store Validator"
description: "Validates store information using Naver API"
inputs:
  path:
    description: "Path to the location.yaml file"
    required: true
    default: "location.yaml"
  naver_client_id:
    description: "Naver API Client ID"
    required: true
  naver_client_secret:
    description: "Naver API Client Secret"
    required: true
outputs:
  warnings:
    description: "Number of warnings (invalid stores)"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv pyyaml

    - name: Create .env file
      shell: bash
      run: |
        echo "INPUT_PATH=${{ inputs.path }}" >> .env
        echo "INPUT_NAVER_CLIENT_ID=${{ inputs.naver_client_id }}" >> .env
        echo "INPUT_NAVER_CLIENT_SECRET=${{ inputs.naver_client_secret }}" >> .env

    - name: Extract store info and validate
      shell: bash
      run: |
        python extract_yaml.py | while IFS=',' read -r name address; do
          python valid_store_naver.py "$name" "$address"
        done > validation_results.txt

    - name: Count warnings
      shell: bash
      run: |
        warnings=$(grep -c "유효하지 않은 가게" validation_results.txt || true)
        echo "warnings=$warnings" >> $GITHUB_OUTPUT
